### PR TITLE
Add action to export full chain PEM

### PR DESCRIPTION
**Pull request by mtancoigne**
Adds an action to export a certificate authority's full chain as PEM

### CODE REVIEW

**Review by neomilium — APPROVED** [review]

**Comment by smortex** [comment]
This seems broken:

1. Since a `CertificateAuthority` is a kind of `Certificate`, the code may better fit in the `Certificate` class;
2. A Certificate[Authority] issuer might not be a root certificate.  We need to include _all_ parents in order to build a full certificate chain.

**Comment by neomilium** [comment]
> This seems broken:

But it works :-)

>     1. Since a `CertificateAuthority` is a kind of `Certificate`, the code may better fit in the `Certificate` class;
OK

>     2. A Certificate[Authority] issuer might not be a root certificate.  We need to include _all_ parents in order to build a full certificate chain.
That's this code do!

**Comment by smortex** [comment]
D'oh, I missed the "recursion" :clown_face:

**Comment by mtancoigne** [comment]
> Since a `CertificateAuthority` is a kind of Certificate, the code may better fit in the `Certificate` class;

My bad, I thought chains were only required for CAs.

**Pull request merged**
