### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mtancoigne**
Update Node and Ruby dependencies. It fixes security alerts on `activerecord` (<6.0.3.5), `actionpack` (<6.0.3.5) and `nokogiri` (<1.11.0). 

The only package causing a security report is node's `ini` one (v1.3.5), locked because of some dependecies for `@rails/webpacker` requiring it. Updating `@rails/webpacker` to the last version won't change anything.

### CODE REVIEW

**Review by smortex — DISMISSED** [review]
I guess the `webpacker` dependency is a development one and we do not really care about it right?

**Comment by mtancoigne** [comment]
Well, Rails 6.1 is also out, so I'll upgrade it too

**Comment by smortex** [comment]
That probably make sense.  Maybe we can also prune all the Rails JS stuff if it helps since the application is not relying on all this which was introduced in Rails 6 IIRC.

**Review by neomilium — APPROVED** [review]

**Comment by neomilium** [comment]
@mtancoigne @smortex Ready to merge?

**Review by smortex — APPROVED** [review]

**Pull request merged**
