### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mtancoigne**
This PR fixes _most_ of the [security alerts](https://github.com/opus-codium/pakotoa/security/dependabot).

### CODE REVIEW

**Comment by mtancoigne** [comment]
- Ruby gems
  - `nokogiri` was not updated (1.13.0  needs ruby > 2.5)
- Node pckages
  - `node-forge`, `ansi-regex`, `glob-parent` and `nth-check` were not updated due to their parents requirements.

**Review by smortex — APPROVED** [review]
Looks good.

We can probably drop Ruby < 2.7 support since 2.5 is EOL and 2.6 is in a few days.

Also if we update to Rails 7 we can cut the dependency on all node crap :v:

**Comment by mtancoigne** [comment]
Yep, i'll do this :)

**Comment by smortex** [comment]
> Yep, i'll do this :)

Don't! I nearly finished at $WORK!

**Pull request closed without merging**
